### ISSUE TITLE
iOSサポート

### ISSUE THREAD

**Issue by KenjiroIchise** [DeNA/mempatch#1]
素晴らしいプロジェクトを有難うございます。
本プロジェクトのスコープとしてiOS対応のPRは許可されますでしょうか?

`ptrace`、`/proc/pid/maps`、`/proc/pid/mem`をmachAPIに置換して一部を修正すればほぼそのまま動作可能だと思います。

**Comment by funa-tk** [comment]
はい。iOS対応のPRにつきましても、お待ちしております！

**Comment by KenjiroIchise** [comment]
迅速なMerge有難うございます!
iOS環境で非jailbreak端末に対応するため、mempatchを共有ライブラリとしてビルドしてlibmempatch.dylibをアプリに埋め込む方式で実装を考えています。
その場合コマンドラインでは入力を受け付けられないため、ネットワーク経由でコマンドを受け付けて結果を返すだけのtcpserverを実装する方式で対応予定です。
宜しくお願いします。
