### ISSUE TITLE
ワークショップ等での利用について

### ISSUE THREAD

**Issue by DoranekoSystems** [DeNA/mempatch#6]
いつも参考にさせて頂いております。
教育目的のワークショップでこちらのプロジェクトを利用させて頂くのは問題ないでしょうか？
各OSで他のプロセスのメモリを読み書きしたり検索する方法の原理を学び、対策に役立てるという内容です。

**Comment by funa-tk** [comment]
ご連絡をありがとうございました！
このプロジェクトを公開した意義にも合致しており、とても良い試みだと思いました。
ワークショップでの利用ですが、全く問題ございません。
